
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 19 18:25:13 CET 2013
//----------------------------------------------------

package pl.edu.pjwstk.jps.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int GROUP_AS = 42;
  public static final int DIVIDE = 12;
  public static final int STRING_LITERAL = 7;
  public static final int XOR = 17;
  public static final int LESS_EQ_THAN = 21;
  public static final int MINUS = 10;
  public static final int WHERE = 43;
  public static final int BOOLEAN_LITERAL = 6;
  public static final int NOT = 14;
  public static final int AND = 15;
  public static final int IN = 38;
  public static final int OR = 16;
  public static final int COMMA = 34;
  public static final int FOR_ALL = 39;
  public static final int BAG = 35;
  public static final int PLUS = 9;
  public static final int MULTIPLY = 11;
  public static final int MIN = 28;
  public static final int DOT = 33;
  public static final int LEFT_ROUND_BRACKET = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MODULO = 13;
  public static final int EXISTS = 30;
  public static final int JOIN = 44;
  public static final int FOR_ANY = 40;
  public static final int EQ = 18;
  public static final int UNIQUE = 29;
  public static final int AVG = 25;
  public static final int UNION = 37;
  public static final int NOT_EQ = 19;
  public static final int MINUS_SET = 31;
  public static final int SUM = 24;
  public static final int DOUBLE_LITERAL = 5;
  public static final int AS = 41;
  public static final int COUNT = 26;
  public static final int INTERSECT = 32;
  public static final int STRUCT = 36;
  public static final int MORE_EQ_THAN = 23;
  public static final int MORE_THAN = 22;
  public static final int LESS_THAN = 20;
  public static final int MAX = 27;
  public static final int RIGHT_ROUND_BRACKET = 3;
  public static final int INTEGER_LITERAL = 4;
  public static final int IDENTIFIER = 8;
}

