
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 16 21:35:22 CET 2013
//----------------------------------------------------

package pl.edu.pjwstk.jps.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int AND = 8;
  public static final int MULTIPLY = 4;
  public static final int PLUS = 2;
  public static final int OR = 9;
  public static final int SUM = 17;
  public static final int BOOLEAN_LITERAL = 27;
  public static final int NOT = 7;
  public static final int IDENTIFIER = 29;
  public static final int MODULO = 6;
  public static final int LESS_EQ_THAN = 14;
  public static final int MORE_THAN = 15;
  public static final int STRING_LITERAL = 28;
  public static final int COMMA = 22;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int LESS_THAN = 13;
  public static final int MINUS = 3;
  public static final int AVG = 18;
  public static final int error = 1;
  public static final int RIGHT_ROUND_BRACKET = 24;
  public static final int MORE_EQ_THAN = 16;
  public static final int EQ = 11;
  public static final int INTEGER_LITERAL = 25;
  public static final int MIN = 21;
  public static final int LEFT_ROUND_BRACKET = 23;
  public static final int XOR = 10;
  public static final int MAX = 20;
  public static final int COUNT = 19;
  public static final int NOT_EQ = 12;
  public static final int DOUBLE_LITERAL = 26;
}

